api/urls.py
from django.urls import path
from api import views
from api.api import UserAPI

urlpatterns = [
    path('example-post/', views.example_post, name="example-post"),
    path('example-get/', views.example_get, name="example-get"),
    path('create_user/', UserAPI.as_view(), name='api_create_user'),
]

mproject_prueba/urls.py
from django.contrib import admin
from django.urls import path, include
from api import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('polls/', include('polls.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('getForm/', views.getForm, name='getForm'),
    path('create/', views.create, name='create'),
    path('detail/<int:question_id>', views.detail, name='detail'),

    path('getFormModelForm/', views.getFormModelForm, name='getFormModelForm'),
    path('createWithModelForm/', views.createWithModelForm, name='createWithModelForm'),
]

api/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.
class Persona(models.Model):
    nombre = models.CharField(max_length=100, verbose_name="Nombre Persona")    
    apellido = models.CharField(max_length=100, null=True, blank=True)
    dni = models.CharField(max_length=8, unique=True)


class Familia(models.Model):
    PARENTESCOS_CHOICES = [
        ('padre', 'Padre'),
        ('hermano', 'Hermano/a'),
        ('madre', 'Madre'),
        ('hijo', 'Hijo/a'),
        ('esposo', 'Esposo/a'),
    ]

    nombre = models.CharField(max_length=100, null=True, blank=True)
    parentesco = models.CharField(max_length=50, null=True, blank=True, choices=PARENTESCOS_CHOICES)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE,  default='1')

polls/forms.py
from django.forms import ModelForm
from .models import Persona

class PersonaForm(ModelForm):
    class Meta:
        model = Persona
        fields = ['nombre', 'apellido', 'dni']

api/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from rest_framework import viewsets
from api.serializers import UserSerializerMeta

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all()
    serializer_class = UserSerializerMeta

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Persona
from .forms import PersonaForm


# Create your views here.

def index(request):
    personas = Persona.objects.all()

    return render(request, 'polls/listar.html', {'personas' : personas})

def getForm(request):
    return render(request, 'polls/index.html')

def create(request):
    if request.method == 'POST':
        persona = Persona()

        persona.nombre = request.POST['nombre']
        persona.apellido = request.POST['apellido']
        persona.dni = request.POST['dni']

        persona.save()

        return HttpResponseRedirect('/polls')

def detail(request, question_id):
    persona = Persona.objects.get(id=question_id)

    return render(request, 'polls/detalles.html', {'persona' : persona})


###############################################################

###############################################################
def getFormModelForm(request):
    form = PersonaForm()

    return render(request, 'polls/createFormModelForm.html', {'formPersona':form})


def createWithModelForm(request):
    if request.method == 'POST':
        form = PersonaForm(request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/polls')

polls/templates/polls/createFormModelForm.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Primer Hola Mundo</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}">
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	    <a class="btn btn-info" href="{% url 'polls:index' %}">Regresar</a>
	</nav>

	<br><br>

	<div class="container">
		<div class="row">
		    <div class="col-md-6 offset-md-3">
		    	<form action="{% url 'polls:create' %}" method="post">
		    		{% csrf_token %}
				  
                    {{ formPersona }}

                    <br>

				  <button type="submit" class="btn btn-success btn-block">Enviar</button>
				</form>
		    </div>
		 </div>
	</div>

	<script src="{% static 'polls/js/jquery.js' %}" type="text/javascript"></script>
	<script src="{% static 'polls/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'polls/js/custom.js' %}" type="text/javascript"></script>

	<script>
		
		
	</script>
</body>
</html>

polls/templates/polls/detalles.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Listado</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}">
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	    <a class="btn btn-info" href="{% url 'polls:index' %}">Regresar</a>
	</nav>
	<br><br>

	<div class="container">
		<div class="card">
		  <div class="card-header">
		    Detalles Datos
		  </div>
		  <div class="card-body">
		    <h5 class="card-title">{{ persona.nombre }} {{ persona.apellido }} {{ persona.dni }}</h5>
		  </div>
		</div>
	</div>

	<script src="{% static 'polls/js/jquery.js' %}" type="text/javascript"></script>
	<script src="{% static 'polls/js/bootstrap.min.js' %}" type="text/javascript"></script>

	<script>
		
		
	</script>
</body>
</html>

polls/templates/polls/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Primer Hola Mundo</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}">
</head>
<body>

	<br><br>

	<div class="container">
		<div class="row">
		    <div class="col-md-6 offset-md-3">
		    	<form action="{% url 'polls:create' %}" method="post">
		    		{% csrf_token %}
				  <div class="form-group">
				    <label for="exampleInputEmail1">Nombre</label>
				    <input type="text" name="nombre" class="form-control" >
				  </div>

				  <div class="form-group">
				    <label for="exampleInputEmail1">Apellido</label>
				    <input type="text" name="apellido" class="form-control" >
				  </div>

				  <div class="form-group">
				    <label for="exampleInputEmail1">DNI</label>
				    <input type="text" name="dni" class="form-control">
				  </div>

				  <button type="submit" class="btn btn-success btn-block">Enviar</button>
				</form>
		    </div>
		 </div>
	</div>

	<script src="{% static 'polls/js/jquery.js' %}" type="text/javascript"></script>
	<script src="{% static 'polls/js/bootstrap.min.js' %}" type="text/javascript"></script>

	<script>
		
		
	</script>
</body>
</html>

polls/templates/polls/listar.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Listado</title>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}">
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	    <a class="btn btn-info" href="{% url 'polls:getForm' %}">Registrar</a> &nbsp;&nbsp;&nbsp;&nbsp;
	    <a class="btn btn-info" href="{% url 'polls:getFormModelForm' %}">Registrar con ModelForm</a>
	</nav>
	<br><br>

	<div class="container">
		<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Nombre</th>
		      <th scope="col">Apellido</th>
		      <th scope="col">DNI</th>
		      <th scope="col">Accion</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for persona in personas %}
		        <tr>
			      <th scope="row">{{ persona.id }} </th>
			      <td>{{ persona.nombre }}</td>
			      <td>{{ persona.apellido }}</td>
			      <td>{{ persona.dni }}</td>
			      <td>
			      	<a class="btn btn-info" href="{% url 'polls:detail' persona.id %}">Ver</button>
			      </td>
			    </tr>
		    {% endfor %}
		    
		  </tbody>
		</table>
	</div>

	<script src="{% static 'polls/js/jquery.js' %}" type="text/javascript"></script>
	<script src="{% static 'polls/js/bootstrap.min.js' %}" type="text/javascript"></script>

	<script>
		
		
	</script>
</body>
</html>